fix: make touch context aware

diff --git a/usr/local/share/tfmake/touch b/usr/local/share/tfmake/touch
--- a/usr/local/share/tfmake/touch
+++ b/usr/local/share/tfmake/touch
@@ -17,33 +17,58 @@ Usage:
 
 Options:
   -h, --help, help  Show this help output.
+  --plan            Touch modified files before 'terraform plan' execution.
+  --apply           Touch modified files before 'terraform apply' execution.
   -f, --files       List of files to touch.
 EOF
   exit
 }
 
+[[ $# -eq 0 ]] && usage
+
+target=""
 files=""
+sep=""
 
-option="${1-}"
-shift
+while :; do
+  case "${1-}" in
+  -h|--help|help)
+    usage
+    ;;
+  --plan|--apply)
+    target="${1:2}"
+    ;;
+  -f|--files)
+    files+="${sep}${2-}"
+    sep=" "
+    shift
+    ;;
+  ?*)
+    printf ">>> Unknown option: %s\n\n" "${1}"
+    usage
+    ;;
+  *)
+    break
+    ;;
+  esac
+  shift
+done
 
-case "${option}" in
--h|--help|help)
-  usage
-  ;;
--f|--files)
-  files="$*"
-  ;;
-*)
-  usage
-  ;;
-esac
+# validations
+if [[ -z "${target}" ]]; then
+  printf ">>> Missing '--plan' or '--apply' option.\n"
+  exit 1
+fi
+
+file::exist_condition \
+  "${DATA_DIR}/${target}/store/modules/keys" \
+  "tfmake init --${target}"
 
 if [[ -z ${files} ]]; then
   printf ">>> No files, anything to do.\n"
 fi
 
-store::basepath "${DATA_DIR}/plan/store"
+store::basepath "${DATA_DIR}/${target}/store"
 store::use modules
 
 modules=$(utils::splitlines "$(kv::keys)")
